# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: GEIA @UFSC
  pt: GEIA @UFSC
email: your-email@domain.com
description:
  en: GEIA is the artificial intelligence and machine learning club at UFSC
  pt: GEIA é o grupo de estudos em inteligência artificial e machine learning da UFSC
index:
  en:
  pt: inicio.html
feed:
  en: /feed.xml
  pt: /feed.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geia-ufsc.github.io" # the base hostname & protocol for your site
telegram_link: KRVDdhN0o0Gwky2NftJ6XA
github_username: GEIA-UFSC
facebook: GEIA-UFSC

# Build settings
markdown: kramdown
